### ISSUE TITLE
Scene Switching

### ISSUE THREAD

**Issue by TURX** [aitc19x/VR-JC#1]
**Describe the bug**
The head position cannot be kept after switching scenes.

**To Reproduce**
1. Start the program
2. Click on any button
3. See error

**Expected behavior**
Switching with the head position kept

**Comment by TURX** [comment]
日本側へ：

非同期のシーンスイッチングを試して失敗しましたが、時間があればこのissueを修復してください。

- 非同期のシーンスイッチングのステップス：
  1. 古いシーンで新しいシーンをロードする；
  2. 新しいシーンで古いシーンをアンロードする。
- 非同期のシーンスイッチングのエラー：古いシーンをアンロードの後にプログラムを動きません。
- 同期（通常）のシーンスイッチングのエラー：新しいシーンをロードの後に視角をリセットされます。

よろしくお願い致します。

@sei0o

**Comment by TURX** [comment]
Stored the rotation of the camera, the switching process still fails. For I am using Ubuntu, the support of Unity is poor, and I cannot use traditional debuggers.

カメラの回転を保存したのに、同期のシーンスイッチングのプロセスは未だ失敗です。Ubuntuを使うから、Unity支援は弱いで、伝統的なデバッガを利用できません。

The code is as follows:

コードは次の通りです：

WelcomeScene/ButtonHandler.cs
```cs
private void SaveCamera()
{
    if (Camera.main == null) return;
    var rotation = Camera.main.transform.eulerAngles;
    PlayerPrefs.SetFloat("camera_x", rotation.x);
    PlayerPrefs.SetFloat("camera_y", rotation.y);
    PlayerPrefs.SetFloat("camera_z", rotation.z);
}

public void ShowCopyright()
{
    SaveCamera();
    SceneManager.LoadScene("CopyrightScene");
}
```

CopyrightScene/ButtonHandler.cs
```cs
public void Start()
{
    Camera.main.transform.eulerAngles = new Vector3(PlayerPrefs.GetFloat("camera_x"),
        PlayerPrefs.GetFloat("camera_y"), PlayerPrefs.GetFloat(("camera_z")));
}
```

**Comment by TURX** [comment]
[このドキュメント](https://docs.unity3d.com/Manual/QuaternionAndEulerRotationsInUnity.html)よりEuler anglesの制限を示します。

From [this document](https://docs.unity3d.com/Manual/QuaternionAndEulerRotationsInUnity.html) we can find the limitation of Euler angles.

> Limitation: Euler angles suffer from Gimbal Lock. When applying the three rotations in turn, it is possible for the first or second rotation to result in the third axis pointing in the same direction as one of the previous axes. This means a “degree of freedom” has been lost, because the third rotation value cannot be applied around a unique axis.

それから、quaternionsを切り替えました。指定されたカメラも使いでいます。

So we changed to quaternions. Also, we are now using a specified camera.

ところが問題を解決できません。

However, the problem still exists.

WelcomeScene/ButtonHandler.cs
```csharp
private void SaveCamera()
{
    if (Camera.main == null) return;
    var rotation = Camera.main.transform.rotation;
    PlayerPrefs.SetFloat("camera_x", rotation.x);
    PlayerPrefs.SetFloat("camera_y", rotation.y);
    PlayerPrefs.SetFloat("camera_z", rotation.z);
    PlayerPrefs.SetFloat("camera_w", rotation.w);
}
```

CopyrightScene/ButtonHandler.cs
```csharp
public Camera mainCamera;

public void Start()
{
    mainCamera.transform.rotation = new Quaternion(PlayerPrefs.GetFloat("camera_x"), PlayerPrefs.GetFloat("camera_y"), PlayerPrefs.GetFloat("camera_z"), PlayerPrefs.GetFloat("camera_w"));
}
```

**Comment by TURX** [comment]
次のコードを利用してテストを行って問題が見つかりました：いつでも回転を更新して回転を維持できます。

Using the following code to run the tests, we have found the problem: the rotation can be maintained when always updating the rotation.

こんな予想外な問題を生じて未だ解決方法が中国側にありません。お願い致します。 @sei0o 

The problem is unexpected and the China side currently has no solution for it. Please fix it if you have the solution or we can communicate more about this problem.

CopyrightScene/ButtonHandler.cs
```csharp
private int unixTimestamp;

private bool transformedMainCamera = false;

public void Start()
{
    unixTimestamp = (Int32)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
}

private int GetUnixTime() {
    return (DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
}

public void Update()
{
    if (!transformedMainCamera)
    {
        Camera.main.transform.rotation = new Quaternion(PlayerPrefs.GetFloat("camera_x"), PlayerPrefs.GetFloat("camera_y"), PlayerPrefs.GetFloat("camera_z"), PlayerPrefs.GetFloat("camera_w"));
        if (GetUnixTime() - unixTimestamp > 3) transformedMainCamera = true;
    }
}
```

**Comment by sei0o** [comment]
Sorry for not spending time in this issue. I'll tackle the problem this night and at night in next Sunday (well, we have some kind of security contest this weekend)

**Comment by TURX** [comment]
この問題を対して新しい考えをしました。Update関数の中に回転を変えるから、妨害がFixedUpdateにあるかもと思います。それからGoogle VR SDKを疑いました。オンラインで検索してGVR SDKのRecenter関数をコールするのは必要かものを見ました。協力して解法は見込みです。セキュリティコンテストはご武運を祈ります。

**Comment by TURX** [comment]
スマホでアプリをテストしてこの問題がなくなったのでこのissueをここで閉じる。
