### ISSUE TITLE
3DoF Panorama View

### ISSUE THREAD

**Issue by TURX** [aitc19x/VR-JC#10]
Just the same as the VR section of Google Expeditions, easier to implement.

**Comment by BruceZhou-code** [comment]
Rather a 6DoF model, creating a 3DoF panorama photo is way easier. I took 27 pictures of my room, constantly changing the shooting angle and making sure that each two pictures have at least 20% overlapped portion. Then, I used the software [PTGui (free trial edition) ](https://www.ptgui.com/) to figure out a [panorama picture](https://user-images.githubusercontent.com/63290199/82210484-c2e60580-9941-11ea-8955-b62c93d4ac9a.jpg). Through the free software [DevalVR player](https://github.com/aitc19x/VR-JC/files/4643940/VideoPanoramasPlayer.0.9.3.3.zip), the picure can be seen in panorama view. Still, the view is not perfect, and I wil try making it better.

**Comment by TURX** [comment]
The purpose of this issue is to implement a scene in Unity to display the panorama image.

**Comment by BruceZhou-code** [comment]
I see. I found a post on CSDN, which is clear about how to set a panorama image as a scene in Unity. [Here](https://blog.csdn.net/wenxuhonghe/article/details/88916239) Here is the result. 
![screenshot](https://user-images.githubusercontent.com/63290199/82310057-7a3c5400-99f6-11ea-8299-17c3cb08617a.png)

**Comment by sei0o** [comment]
It looks like the clock is flipped horizontally ... 🤔

**Comment by BruceZhou-code** [comment]
Yeah.. The whole scene is inverted horizontally. It can be solve by setting the meterial's tilling value from x = 1 to x = -1.
![screenshot2](https://user-images.githubusercontent.com/63290199/82406365-fd15eb00-9a98-11ea-86ac-9c186d881963.png)

**Comment by TURX** [comment]
You can create such a scene in this project and enable it to receive parameters from the menu scene (e.g. property of a menu object pointing to the path of the panoroma photo, and reading of the properties of floating introduction). Then you can open a pull request to merge the changes to master branch.

**Comment by TURX** [comment]
This issue is implemented by pull request #19.
