### ISSUE TITLE
missing font?

### ISSUE THREAD

**Issue by sei0o** [aitc19x/VR-JC#17]
**Describe the bug**

Noticed that all of the Texts are invisible. I thought that was a problem of Unity for Linux at first until I found "Missing (font)" on the Inspector. Someone has added fonts that has been available only on their own environments, maybe? 

![missing](https://user-images.githubusercontent.com/5410901/81410769-42bee380-917c-11ea-8d87-e5920a357671.png)

**Comment by TURX** [comment]
The fonts are in /Assets/Noto-Sans-CJK-JP which is a submodule of this repository. If you open Unity at the first time after updating the submodules, the fonts may work.

**Comment by sei0o** [comment]
You are right, it worked.
